# Backend Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: yolo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: edensel/img-b:v2.0.0  
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/akal  # Correctly points to the mongo-service
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: my-docker-secret  # If using a private registry

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # Exposing the backend service externally if needed
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
